version: 1

global:
  default_ref: "main"

modules:
  - name: "01.Module_1"
    enabled: true
    repo: "nguyenvan-huan/Module_1"
    ref: "main"

    build:
      type: "build_binary"   # copy_source | build_binary | download_artifact
      working_directory: "."
      install_script: "scripts/install.sh"
      build_script: "scripts/publish.sh"
      output_path: "bin/Release/net8.0/linux-x64/publish/Test"

    artifact:
      collect_to: "01.PARETTE_System/01.Module_1/"

  - name: "02.Module_2"
    enabled: true
    repo: "nguyenvan-huan/Module_2"
    ref: "main"

    build:
      type: "copy_source"
      working_directory: "."
      install_script: ""
      build_script: ""
      output_path: "README.md"

    artifact:
      collect_to: "01.PARETTE_System/02.Module_2/"
