version: 1

global:
  default_ref: "main"

modules:
  - name: "01.Module_1"
    enabled: true
    repo: "nguyenvan-huan/Module_1"
    ref: "main"

    execution:
      working_directory: "."
      install_script: "scripts/install.sh"
      build_script: "scripts/publish.sh"
      module_package_script: "scripts/package.sh"

    output:
      package_output_path: ".github/package/"
      collect_to: "01.PARETTE_System/01.Module_1/"

  - name: "02.Module_2"
    enabled: true
    repo: "nguyenvan-huan/Module_2"
    ref: "main"

    execution:
      working_directory: "."
      install_script: ""
      build_script: ""
      module_package_script: "scripts/package.sh"

    output:
      package_output_path: ".github/package/"
      collect_to: "01.PARETTE_System/02.Module_2/"
